# Generated by Django 4.1.3 on 2022-11-24 18:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('room', '0002_room2'),
    ]

    operations = [
        migrations.AlterField(
            model_name='room2',
            name='content',
            field=models.SlugField(blank=True),
        ),
    ]
