# Generated by Django 4.1.3 on 2022-11-25 12:04

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('room', '0003_alter_room2_content'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Room2',
        ),
    ]
