# Generated by Django 4.1.3 on 2022-11-27 16:21

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('room', '0005_rooms_delete_room'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Rooms',
        ),
    ]
