# Generated by Django 4.1.3 on 2022-12-10 14:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('database', '0003_cards'),
    ]

    operations = [
        migrations.AddField(
            model_name='rooms',
            name='cards',
            field=models.TextField(default='jhbsa'),
            preserve_default=False,
        ),
    ]
